### ISSUE TITLE
precompiled image doesn't have wifi

### ISSUE THREAD

**Issue by netmonk** [chuangzhu/nixos-sun20iw1p1#2]
Hello 
is there a way to build this without running nixos from host os ?
Also the prebuilt image doesnt have wifi driver 
```
[nixos@nixos:~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: usb0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether f2:c2:e7:31:53:29 brd ff:ff:ff:ff:ff:ff

```

**Comment by chuangzhu** [comment]
The prebuilt image with WiFi is uploading. It's possible to build on non-NixOS, see https://discourse.nixos.org/t/how-to-configure-qemu-binfmt-wrapper-on-a-non-nixos-machine/7879/6.

**Comment by chuangzhu** [comment]
Uploaded https://github.com/chuangzhu/nixos-sun20iw1p1/releases/tag/rtl8723ds

**Comment by netmonk** [comment]
Thank you very much
