### ISSUE TITLE
sun6i-rtc console flooding

### ISSUE THREAD

**Issue by netmonk** [chuangzhu/nixos-sun20iw1p1#3]
i tryed your latest release image.
After activating network like in your video i got this line repeated like a while loop keeping the console unsable : 

```
[  716.938777] sun6i-rtc 7090000.rtc: rtc is still busy.
[  717.938510] sun6i-rtc 7090000.rtc: rtc is still busy.
[  717.938510] sun6i-rtc 7090000.rtc: rtc is still busy.
[  718.938234] sun6i-rtc 7090000.rtc: rtc is still busy.
[  718.938234] sun6i-rtc 7090000.rtc: rtc is still busy.
[  719.937967] sun6i-rtc 7090000.rtc: rtc is still busy.
[  719.937967] sun6i-rtc 7090000.rtc: rtc is still busy.
[  720.937696] sun6i-rtc 7090000.rtc: rtc is still busy.
[  720.937696] sun6i-rtc 7090000.rtc: rtc is still busy.
```

 Note that connecting with ssh is smoother experience as far as the tty assocaited isnt flooded with the kernel message.

**Comment by chuangzhu** [comment]
The Lichee RV board doesn't have a RTC battery slot, so the on-chip RTC is actually not powered. You can temporarily suppress the warning using

```shellsession
$ sudo sysctl kernel.printk=3
```

**Comment by chuangzhu** [comment]
Not on the latest image.
